openapi: 3.0.4
info:
  title: Student Dashboard API
  description: This is a documentation for the student Dashboard
  version: 1.0.12
paths:
  /ping:
    get:
      tags:
        - ping
      summary: This tests the server
      description: 
      responses:
        '200':
          description: Successful operation